test2

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,35 +14,36 @@ jobs:
         with:
           fetch-depth: 0
           sparse-checkout: |
-            docs
-            includes
-      - uses: actions/setup-python@v4
+            docs/
+            includes/
+      - name: Set up Python
+        uses: actions/setup-python@v4
         with:
-          python-version: 3.x
-      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
-      - uses: actions/cache@v3
+          python-version: '3.x'
+      - name: Cache dependencies
+        uses: actions/cache@v3
         with:
-          key: mkdocs-material-${ env.cache_id }
+          key: mkdocs-material-${{ github.run_id }}
           path: .cache
           restore-keys: |
             mkdocs-material-
-      - run: pip install mkdocs-git-revision-date-localized-plugin
-      - run: pip install mkdocs-git-authors-plugin
-      - run: pip install mkdocs-git-committers-plugin-2
-      - run: pip install markdown-callouts
-      # - run: pip install mkdocs-minify-plugin
-      - run: pip install mkdocs-rss-plugin
-      # - run: pip install jieba
-      # - run: pip install mkdocs-open-in-new-tab
-      - run: pip install pymdown-extensions
-      - run: pip install mkdocs-encryptcontent-plugin
-      # - run: pip install mkdocs-glightbox
-      # - run: pip install "mkdocs-material[imaging]"
-      # - run: pip install mkdocs-statistics-plugin        
-      - run: pip install mkdocs-material 
-      - run: pip install --upgrade --force-reinstall mkdocs-material
-      - run: mkdocs gh-deploy --force
-
-
-
-
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install mkdocs-git-revision-date-localized-plugin
+          pip install mkdocs-git-authors-plugin
+          pip install mkdocs-git-committers-plugin-2
+          pip install markdown-callouts
+          pip install mkdocs-rss-plugin
+          pip install pymdown-extensions
+          pip install mkdocs-encryptcontent-plugin
+          pip install mkdocs-material
+      - name: Deploy to GitHub Pages
+        run: |
+          if [ -d "docs" ]; then
+            echo "Docs directory exists. Proceeding with deployment."
+            mkdocs gh-deploy --force
+          else
+            echo "Docs directory does not exist. Deployment aborted."
+            exit 1
+          fi
